module.exports = {
  AbortError: [
    {
      type: 'exception',
      spec: 'webidl',
      shortname: 'webidl',
      status: 'current',
      uri: '#aborterror',
    },
  ],
  'event handler': [
    {
      type: 'dfn',
      spec: 'html',
      shortname: 'html',
      status: 'snapshot',
      uri: 'webappapis.html#event-handlers',
    },
  ],
  'host parsing': [
    {
      type: 'dfn',
      spec: 'url',
      shortname: 'url',
      status: 'snapshot',
      uri: '#concept-host-parser',
    },
  ],
  '': [
    {
      type: 'enum-value',
      spec: 'referrer-policy-1',
      shortname: 'referrer-policy',
      status: 'current',
      uri: '#dom-referrerpolicy',
      for: ['ReferrerPolicy'],
    },
    {
      type: 'enum-value',
      spec: 'fetch',
      shortname: 'fetch',
      status: 'current',
      uri: '#dom-requestdestination',
      for: ['RequestDestination'],
    },
    {
      type: 'enum-value',
      spec: 'xhr',
      shortname: 'xhr',
      status: 'current',
      uri: '#dom-xmlhttprequestresponsetype',
      for: ['XMLHttpRequestResponseType'],
    },
  ],
  Baseline: [
    {
      type: 'interface',
      spec: 'font-metrics-api-1',
      shortname: 'font-metrics-api',
      status: 'current',
      uri: '#baseline',
    },
  ],
  baseline: [
    {
      type: 'dfn',
      spec: 'svg2',
      shortname: 'svg',
      status: 'snapshot',
      uri: 'text.html#TermBaseline',
    },
    {
      type: 'dfn',
      spec: 'svg2',
      shortname: 'svg',
      status: 'current',
      uri: 'text.html#TermBaseline',
    },
  ],
  script: [
    {
      type: 'enum-value',
      spec: 'fetch',
      shortname: 'fetch',
      status: 'current',
      uri: '#dom-requestdestination-script',
      for: ['RequestDestination'],
    },
    {
      type: 'element',
      spec: 'html',
      shortname: 'html',
      status: 'snapshot',
      uri: 'scripting.html#script',
    },
    {
      type: 'dfn',
      spec: 'html',
      shortname: 'html',
      status: 'snapshot',
      uri: 'webappapis.html#concept-script',
    },
    {
      type: 'element',
      spec: 'svg',
      shortname: 'svg',
      status: 'snapshot',
      uri: 'script.html#ScriptElement',
    },
    {
      type: 'element',
      spec: 'svg2',
      shortname: 'svg',
      status: 'snapshot',
      uri: 'interact.html#elementdef-script',
    },
    {
      type: 'element',
      spec: 'svg2',
      shortname: 'svg',
      status: 'current',
      uri: 'interact.html#elementdef-script',
    },
  ],
  'inherited value': [
    {
      type: 'dfn',
      spec: 'css-cascade-3',
      shortname: 'css-cascade',
      status: 'snapshot',
      uri: '#inherited-value',
    },
    {
      type: 'dfn',
      spec: 'css-cascade-3',
      shortname: 'css-cascade',
      status: 'current',
      uri: '#inherited-value',
    },
    {
      type: 'dfn',
      spec: 'css-cascade-4',
      shortname: 'css-cascade',
      status: 'snapshot',
      uri: '#inherited-value',
    },
    {
      type: 'dfn',
      spec: 'css-cascade-4',
      shortname: 'css-cascade',
      status: 'current',
      uri: '#inherited-value',
    },
  ],
};
